services:
  db:
    image: mysql:8.0
    container_name: minimal_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=minimal_api
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: minimal_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__MySql: "Server=db;Database=minimal_api;Uid=root;Pwd=root;"
      Jwt: "minimal-api-super-secret-key-32bytes-minimum-2025"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5004:80"
volumes:
  dbdata:
