name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore minimal-api.sln

      - name: Build
        run: dotnet build minimal-api.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test minimal-api.sln --configuration Release --no-build --verbosity normal
