name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-zip-and-release:
    name: Build .NET publish and attach to GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish API
        run: |
          dotnet publish ./Api/mininal-api.csproj -c Release -o ./publish/api /p:UseAppHost=false

      - name: Create ZIP artifact
        run: |
          VERSION="${GITHUB_REF_NAME}"
          cd publish/api
          zip -r "../minimal-api-${VERSION}.zip" .
          ls -lah ../

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            publish/minimal-api-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-container:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./Api
          file: ./Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/minimal-api:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/minimal-api:latest

      - name: Login to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./Api
          file: ./Api/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/minimal-api:${{ github.ref_name }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/minimal-api:latest
